### ISSUE TITLE
nginx gateway problem was: docker containers crashing was: problem with the exec postgres step

### ISSUE THREAD

**Issue by affluent-bilby-classifieds** [francoisruty/fruty_react-admin#2]
Hi Fruty,

Firstly I want to thank you immensely for making this docker file and instructions available.

Having said that I am stuck at the part of the instructions where we need to exec postgress:

docker-compose exec postgres /bin/bash psql --username=fruty \i /init/init.sql \q exit
/usr/bin/psql: line 19: use: command not found
/usr/bin/psql: line 20: use: command not found
/usr/bin/psql: line 21: use: command not found
/usr/bin/psql: line 22: use: command not found
/usr/bin/psql: psql: line 24: syntax error near unexpected token `$version,'
/usr/bin/psql: psql: line 24: `my ($version, $cluster);'

To troubleshoot I went into portainer and opened the console as postgres and entered:
postgres /bin/bash psql --username=fruty \i /init/init.sql
FATAL:  unrecognized configuration parameter "username"

I'm not sure what I should try next. Any suggestions?

Edit: I just noticed there are 4 other containers that stop within seconds of starting:

fruty_react-admin_postgres_1 | running |   | fruty_react-admin | postgres:9.6 | 2020-06-14 10:39:38 | - | administrators
-- | -- | -- | -- | -- | -- | -- | --
exciting_satoshi | running |   | - | portainer/portainer | 2020-05-30 20:25:01 | 9000:9000 | administrators
fruty_react-admin_nginx-front_1 | stopped |   | fruty_react-admin | nginx:stable | 2020-06-14 10:39:46 | - | administrators
fruty_react-admin_back_1 | stopped |   | fruty_react-admin | node:10 | 2020-06-14 10:39:40 | - | administrators
fruty_react-admin_pgweb_1 | stopped |   | fruty_react-admin | sosedoff/pgweb | 2020-06-14 10:39:40 | - | administrators
fruty_react-admin_front_1 | stopped |   | fruty_react-admin | node:10 | 2020-06-14 10:39:38 | - | administrators

I deleted all the fruty containers and started again. They all stopped except:

fruty_react-admin_pgweb_1 |   | fruty_react-admin | 
fruty_react-admin_postgres_1

I will enter the logs for each stopped container:

2020/06/14 03:19:40 [emerg] 1#1: host not found in upstream "front" in /etc/nginx/nginx.conf:49

fruty_react-admin_nginx-front_1 
nginx: [emerg] host not found in upstream "front" in /etc/nginx/nginx.conf:49

test@0.0.0 dev /home/app

> nodemon server.js

sh: 1: nodemon: not found

npm ERR! code ELIFECYCLE

npm ERR! syscall spawn

npm ERR! file sh

npm ERR! errno ENOENT

npm ERR! test@0.0.0 dev: `nodemon server.js`

npm ERR! spawn ENOENT



and I get the same in fruty_react-admin_back_1

**Comment by francoisruty** [comment]
hello, the README is damaged by github, some carriage returns are missing
docker-compose exec postgres /bin/bash psql --username=fruty \i /init/init.sql \q exit
---->
docker-compose exec postgres /bin/bash 
psql --username=fruty 
\i /init/init.sql 
\q 
exit

Those must be run one by one, not all at once

For the stopped containers, that's normal, back and front will not start unless you installed the dependencies first with npm install, it's all in the README
You have to do a docker-compose run to force start the containers and log into them, and install the dependencies with npm install

**Comment by affluent-bilby-classifieds** [comment]
Hi Fruty! 
Thank you so much. I woke up this morning to your reply and I have had another go. In the mean-time (yesterday) I had been doing the tutorial on the react-admin website. 

I followed the instructions and I got much further this time.
All the containers are up except for: fruty_react-admin_back_run_c9c33a239347 
I get to the very last step: curl -X POST http://localhost:3000/api/create_user -H 'Cache-Control: no-cache' -H 'Content-Type: application/json' -d '{ "email": "test@test.fr", "password": "Password1" }'
and get a 502 bad gateway.
Port 3000 is running with the login screen. Trying to login gives me a red Bad Gateway message. 

I'm not sure why the container stopped. In the log is has a long message for npm install then # exit
, at the end.
 
I have started the container again and it hasn't crashed. I still get 502 bad gateway from my terminal.
The only thing is I did have a bunch of other docker containers running from other projects I had been testing. I have stopped all those now but still getting the same issue. Perhaps I should go back and follow the instructions again incase one of the other containers was interfering with the steps in the read-me somehow.

**Comment by francoisruty** [comment]
hello, *_run containers are not supposed to be up, those are the containers you created to run the npm install
I see on your table that the back container is up so this is good
try stopping and restarting nginx-front

Sometimes, when nginx is used as a reverse proxy and a proxied container starts after nginx is up, the connection is not made
nginx-front should be up last, always

**Comment by affluent-bilby-classifieds** [comment]
Thank you. It did say nginx on that 502 bad gateway message I was getting from curl. I have tried restarting the nginx container but that didn't help. I then tried stopping it and starting it. I then tried stopping it and restarting all the other containers. I have made sure they are back up and staying up.  I have now started the nginx container again. 
I am still getting the bad gateway message:

> curl -X POST http://localhost:3000/api/create_user -H 'Cache-Control: no-cache' -H 'Content-Type: application/json' -d '{ "email": "test@test.fr", "password": "Password1" }'
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

Is there a way I can manually establish the connection?
Thank you for your help.

**Comment by francoisruty** [comment]
hello, did you change anything on docker-compose.yml, or anything else?

What are the logs from the back container?

When I git clone this repo and follow the exact instructions from README.sh to the letter, I have no problem whatsoever

**Comment by affluent-bilby-classifieds** [comment]
> hello, did you change anything on docker-compose.yml, or anything else?
> 
> What are the logs from the back container?
> 
> When I git clone this repo and follow the exact instructions from README.sh to the letter, I have no problem whatsoever

The only change I have made is to const corsOptions =  {
  origin: 'http://localhost:3000'
};

I did that in a copy of the program folder and rebuilt. I can easily go back.

I think the issue with with the postgres backend somewhere.

**Comment by affluent-bilby-classifieds** [comment]
I have got into the console for "back"
root@9e7e9f71b54d:/# cd /home/app
root@9e7e9f71b54d:/home/app# npm install bcrypt

Now:
curl -X POST http://localhost:3000/api/create_user -H 'Cache-Control: no-cache' -H 'Content-Type: application/json' -d '{ "email": "test@test.fr", "password": "Password1" }'
{"result":"user created."}chris@reactcore:~/my-app/fruty_react-admin$

**Comment by francoisruty** [comment]
hello, glad you got it working!

**Comment by affluent-bilby-classifieds** [comment]
Thank you. I am so happy too. :)
