### ISSUE TITLE
RFI: Adding additional custom routes for new ra resources

### ISSUE THREAD

**Issue by caston1981** [francoisruty/fruty_react-admin#5]
Hi Fruty,

Thank you again for making this great project. I hope you are well.

The current fork I am working on is at: https://github.com/affluent-bilby-classifieds/prisma_ra-cb-menu

I am just adding my own resource now in the form of a simple contacts database.

I have done this with in a similar project that uses post-graphile (https://github.com/affluent-bilby-classifieds/react-admin-and-postgraphile-playground). I have also started working on a menu data-base resource  but I've had further issues once setting up referential integrity. I don't expect you to help me with that I am just explaining where I am coming from. I wanted to try again with the ~~prisma~~ data provider to see if I had more success getting it up and running.

I tried to do the same with your project and I now find myself getting a 404 error because I don't have a custom route API.
I found this in server.js

`app.use('/api/items', require('./routes/items'));`

I also found the "routes" folder with a items.js (not to be confused with the items.js in the "src" folder.

Can I fairly easy reuse this code for my contacts ra resource by replacing the key words or is it likely to be more difficult?
(from looking at the code it does look like it will be more involved that that as I need to handle individual fields in the database table)

Again I am sorry to brother you and thank you for making this great project. I will be sure to contribute back as much as I can for the benefit of the community.

**Comment by caston1981** [comment]
I realized that your project possibly doesn't even use Prisma. Sorry about the confusion. I would still like to know about adding new the routes though. Thank you. 

PS I have now migrated the project to https://github.com/affluent-bilby-classifieds/express-js_ra-cb-menu 
I will do the security bumps there too.

**Comment by francoisruty** [comment]
hello, this project indeed does not use Prisma, it uses Expressjs for the API (REST)

For :
- using a Prisma backend
- adding RA resources 

you need to check the react-admin documentation

all the best

**Comment by caston1981** [comment]
thanks fruty,

I'm not currently working with Prisma as the [ra-data-opencrud](https://github.com/Weakky/ra-data-opencrud) is not currently maintained and hasn't been updated in two years.

I am, however, working am on a post-graphile [setup](https://github.com/affluent-bilby-classifieds/react-admin-and-postgraphile-playground) which I will run along side [my fork](https://github.com/affluent-bilby-classifieds/express-js_ra-cb-menu) of this Expressjs API version. 
 
I believe I need more than the react-admin documentation as you mentioned it uses Expresjs for the API (REST).

A guide like this could help me learn:
https://medium.com/@purposenigeria/build-a-restful-api-with-node-js-and-express-js-d7e59c7a3dfb

I need this because as I understand I will only get a 404 error when I add resources unless I also write a route for each resource that I add. I would need to rewrite the code to be specific to the database table I am using and each field.


e.g.:
./back/routes/items.js

```
const express = require('express');
const {client, clientsync} = require('../utils');
const router = express.Router();

//NOTE: for react-admin, we must send an array directly in response, not an array wrapped in an object
router.get('/', function(req, res) {

  var text = `
  SELECT *
  FROM items
  `;
  var values = []

  var sort = req.query.sort;
  if (sort !== undefined) {
    sort = JSON.parse(sort);
    if (sort.length == 2 && sort[0] !== null && sort[1] !== null) {
      text = text + ` ORDER BY ` + sort[0] + ` ` + sort[1];
    }
  }

  var range = req.query.range;
  if (range !== undefined) {
    range = JSON.parse(range);
    nb = range[1] - range[0] + 1;
    text = text + ' LIMIT ' + nb;
    text = text + ' OFFSET ' + range[0];

    var count = clientsync.querySync(
      `
      SELECT COUNT(*) FROM items
      `,
      []
    )[0]['count'];

    var rows = clientsync.querySync(text, values);
    res.setHeader('Content-Range', range[0] + '-' + range[1] + '/' + count);

  } else {
    var rows = clientsync.querySync(text, values);
    res.setHeader('Content-Range', '0-' + rows.length + '/' + rows.length);

  }

  res.json(rows);


});

router.get('/:item_id', function(req, res) {

  var rows = clientsync.querySync(
    `SELECT *
    FROM items WHERE id=$1`,
  [req.params.item_id]
  );

  res.json(rows[0]);

});

router.put('/:item_id', function(req, res) {

  var rows = clientsync.querySync(
    `UPDATE items SET title=$2, description=$3 WHERE id=$1 RETURNING *`,
  [req.params.item_id, req.body.title, req.body.description]
  );

  res.json(rows[0]);

});

router.post('/', function(req, res) {

  var rows = clientsync.querySync(
    `INSERT INTO items (id, title, description) VALUES(Default, $1, $2) RETURNING *`,
  [req.body.title, req.body.description]
  );

  res.json(rows[0]);


});

router.delete('/:item_id', function(req, res) {
  var rows = clientsync.querySync(
    `DELETE
    FROM items WHERE id=$1 RETURNING *`,
  [req.params.item_id]
  );

  res.json(rows[0]);

});

module.exports = router;


```
I am of the understanding you wrote this code yourself and it's not from react-admin. So I need to learn enough to be able to write the routes myself and hopefully in doing so improve the project to document and if possible automate the process to make it easier for others.

If we look at the items table:
```
\d+ items
                                               Table "public.items"
   Column    |  Type  |                     Modifiers                      | Storage  | Stats target | Description 
-------------+--------+----------------------------------------------------+----------+--------------+-------------
 id          | bigint | not null default nextval('items_id_seq'::regclass) | plain    |              | 
 title       | text   | not null                                           | extended |              | 
 description | text   | not null                                           | extended |              | 
Indexes:
    "items_pkey" PRIMARY KEY, btree (id)

```

The menucategories table from my fork is the simplest of the other tables and even simpler than the contacts table. So this would be the one I would implement first. I would still need to re-write the route but it would be easier.
```
postgres=# \d+ menucategories
                                                        Table "public.menucategories"
   Column   |           Type           |                          Modifiers                          | Storage  | Stats target | Description 
------------+--------------------------+-------------------------------------------------------------+----------+--------------+-------------
 id         | integer                  | not null default nextval('menucategories_id_seq'::regclass) | plain    |              | 
 catname    | character varying(255)   | not null                                                    | extended |              | 
 created_at | timestamp with time zone | default now()                                               | plain    |              | 
Indexes:
    "menucategories_pkey" PRIMARY KEY, btree (id)
```

But then as I get to my menu table I can see that the structure is very different. The included express.js API code in the route for items.js would need significant re-writing to be able to use this as a RA resource.
```
postgres=# \d+ menu
                                                        Table "public.menu"
   Column    |           Type           |                     Modifiers                     | Storage  | Stats target | Description 
-------------+--------------------------+---------------------------------------------------+----------+--------------+-------------
 id          | integer                  | not null default nextval('menu_id_seq'::regclass) | plain    |              | 
 title       | character varying(255)   | not null                                          | extended |              | 
 category_id | integer                  |                                                   | plain    |              | 
 price       | numeric(8,2)             |                                                   | main     |              | 
 desc1       | character varying(255)   |                                                   | extended |              | 
 isenabled   | boolean                  | not null default true                             | plain    |              | 
 created_at  | timestamp with time zone | default now()                                     | plain    |              | 
Indexes:
    "menu_pkey" PRIMARY KEY, btree (id)
```

PS

I then intend to use referential integrity which is where I came [undone](https://stackoverflow.com/questions/62657963/react-admin-the-dataprovider-threw-an-error-it-should-return-a-rejected-promis) when trying to implement it in the [post-graphile ra repo](https://github.com/affluent-bilby-classifieds/react-admin-and-postgraphile-playground). 

PPS
I will also look into Hasura after finding this [post](https://news.ycombinator.com/item?id=22432616)

**Comment by francoisruty** [comment]
hello, react-admin is a react project, it's only front, no back
It comes with ready-made data providers for various use cases, REST API being one of those

All code in this repo was written by me so yes the routes are from me, and yes, for each resource you need to write CRUD routes

**Comment by caston1981** [comment]
hi Fruty,

Thank you for doing that as well as explaining it to me. I am envious of your programming skills and smart. I am learning a lot and will keep working away. Where possible I will document to help others understand.
Thanks again for your help.
